### PR TITLE
FINCN-148 build with travis-ci.com and upload artifacts to Artifactory

### PR DESCRIPTION
**Pull request by aasaru**

### CODE REVIEW

**Comment by cnangeh** [comment]
This PR looks good to me.

**Comment by awasum** [comment]
Ok. Merge it when ready @Anh3h

**Comment by aasaru** [comment]
Hi!
Could anyone please move on with reviewing and merging my pull requests.
All the PR-s are listed here: https://issues.apache.org/jira/browse/FINCN-148
Thanks!

**Comment by awasum** [comment]
Merged @aasaru . Thanks for your contributions.

**Pull request merged**
