### PR TITLE
FINCN-179 gradle to 4.10.3, FINCN-178 make Travis build forks, ...

### PR DESCRIPTION
**Pull request by aasaru**
FINCN-179 gradle to 4.10.3
FINCN-178 make Travis build forks
FINCN-175 remove Netty warnings
set application to unique port

### CODE REVIEW

**Comment by awasum** [comment]
Ohh, why is this failing? Is this ready to be merged or do you want to add smaller fixes before merging?

its usually a good idea to fix a single isolated issue per PR. It no big deal but something we could adopt in the future...

Thanks for the work @aasaru

**Comment by awasum** [comment]
Seems the "add application-specific banner" commit is causing these failures.
The apache RAT test is what fails.. maybe we can ignore rat checks for the banner.txt file? this affect all the other commits which you added the banner...

**Comment by aasaru** [comment]
> its usually a good idea to fix a single isolated issue per PR. It no big deal but something we could adopt in the future...

Thanks @awasum for feedback. I have tried to squeeze several things here as opening 30+ pull requests is time consuming. I fixed the builds and won't plan to add anything more so if you have time please review.

**Comment by awasum** [comment]
Its Ok to combine several things into one to improve time. You can go ahead and merge. Or @Anh3h Can you review all these and merge? I wont have time.

**Pull request merged**
